// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7V8-yos9JbMEsKhxqKOUQ6ZNg2W3gPPo',
    appId: '1:345226906974:web:c415dbad4a82a49f1293cf',
    messagingSenderId: '345226906974',
    projectId: 'prog-ecommerce',
    authDomain: 'prog-ecommerce.firebaseapp.com',
    storageBucket: 'prog-ecommerce.appspot.com',
    measurementId: 'G-CZ3XBY84N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcGRzzjH55yqx26EirSmkE0kBuoop5sI',
    appId: '1:345226906974:android:c4aa8584de7ff9fa1293cf',
    messagingSenderId: '345226906974',
    projectId: 'prog-ecommerce',
    storageBucket: 'prog-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCWUPeqD8ouZBETFxpxDpMUmJ1vRf3OlY',
    appId: '1:345226906974:ios:41836ead93af224e1293cf',
    messagingSenderId: '345226906974',
    projectId: 'prog-ecommerce',
    storageBucket: 'prog-ecommerce.appspot.com',
    androidClientId: '345226906974-viu7tam41t8hrcoe4685llq1gh2a7had.apps.googleusercontent.com',
    iosClientId: '345226906974-us9t1q31gln8dn1junclgj7fbr5ngh9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCWUPeqD8ouZBETFxpxDpMUmJ1vRf3OlY',
    appId: '1:345226906974:ios:7eaf6d138081de771293cf',
    messagingSenderId: '345226906974',
    projectId: 'prog-ecommerce',
    storageBucket: 'prog-ecommerce.appspot.com',
    androidClientId: '345226906974-viu7tam41t8hrcoe4685llq1gh2a7had.apps.googleusercontent.com',
    iosClientId: '345226906974-0lic4nh3qfon58hm8rjnhiqr8o0ge1g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth.RunnerTests',
  );
}
